#!/usr/bin/env python3

import rospy
from sensor_msgs.msg import JointState
from markers import *
from prfuncs import *
import numpy as np  # Asegúrate de importar numpy si no está ya importado

np.set_printoptions(suppress=True, precision=3)

if __name__ == '__main__':

    rospy.init_node("testInvKine")
    pub = rospy.Publisher('joint_states', JointState, queue_size=1)

    bmarker      = BallMarker(color['RED'])
    bmarker_des  = BallMarker(color['GREEN'])

    # Joint names
    jnames = ['joint_1', 'joint_2', 'joint_3',
              'prismatic_joint', 'joint_4', 
              'joint_5', 'joint_6']

    # Desired position
    xd = np.array([0.5, -0.5, 0.5])
    # Initial configuration
    q0 = np.array([0.0, -1.0, 1.7, 0.0, -2.2, -1.6, 0.2])
    # Inverse kinematics
    q = ikine(xd, q0)

    # Resulting position (end effector with respect to the base link)
    T = fkine(q)
    print('Obtained value:\n', np.round(T,3))
    print('q: ', np.round(q, 3))

    # Red marker shows the achieved position
    bmarker.xyz(T[0:3,3])
    # Green marker shows the desired position
    bmarker_des.xyz(xd)

    # Objeto (mensaje) de tipo JointState
    jstate = JointState()
    # Asignar valores al mensaje
    jstate.header.stamp = rospy.Time.now()
    jstate.name = jnames

    # Asignar la posición de las articulaciones, con los dos ceros añadidos
    jstate.position = q

    # Loop rate (in Hz)
    rate = rospy.Rate(50)
    
    # Continuous execution loop
    while not rospy.is_shutdown():
        jstate.position = q
        # Current time (needed for ROS)
        jstate.header.stamp = rospy.Time.now()
        # Publish the message
        pub.publish(jstate)
        bmarker.publish()
        bmarker_des.publish()
        # Wait for the next iteration
        rate.sleep()
