robot:
  # Publicar los estados de las articulaciones --------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Controladores de trayectoria ----------------------------------------
  joint_trajectory_controller:
    type: effort_controllers/JointTrajectoryController
    joints:
      - joint_1
      - joint_2
      - joint_3
      - prismatic_joint
      - joint_4
      - joint_5
      - joint_6
    gains:
      joint_1: {p: 1, i: 0.0, d: 1}
      joint_2: {p: 1, i: 0.0, d: 1}
      joint_3: {p: 1, i: 0.0, d: 1}
      prismatic_joint: {p: 1, i: 0.0, d: 1}
      joint_4: {p: 1, i: 0.0, d: 1}
      joint_5: {p: 1, i: 0.0, d: 1}
      joint_6: {p: 1, i: 0.0, d: 1}
    constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.01
      joint_1: {trajectory: 0.05, goal: 0.02}
      joint_2: {trajectory: 0.05, goal: 0.02}
      joint_3: {trajectory: 0.05, goal: 0.02}
      prismatic_joint: {trajectory: 0.05, goal: 0.02}
      joint_4: {trajectory: 0.05, goal: 0.02}
      joint_5: {trajectory: 0.05, goal: 0.02}
      joint_6: {trajectory: 0.05, goal: 0.02}
    state_publish_rate: 50
    action_monitor_rate: 10